name = "Torkenmon-server"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "756e1a4d04bfa0a85b3ec2347d19f026afc4f19c2937f07b75373d16e9be4433"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "resources/datapacks"
