name = "TorkenMon Pack Oficial 1.0.0-alpha"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5213659dde518cf505a3009004bb19443c9b41824aa3d45bc56d4b9a2d41823c"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1", "1.21", "1.21.1"]
datapack-folder = "./datapacks"
