name = "TorkenMon Pack Oficial 1.0.0-alpha"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0309d28743b17227f916508df1369a43898f2dfae1c027d71c1fa6a45b518a7"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1", "1.21", "1.21.1"]
datapack-folder = "./datapacks"
