name = "Torkenmon-server"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8280d49510ce2ec39df03acad222833d4602e8612c920fb4854d7cfae178ead"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-folder = "./datapacks"
