name = "TorkenMon Pack Oficial 1.0.0-alpha"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "876426fcf66f24d5ffd6158b3212e84751876c3529c8bcbaf57d2bdc4758ba11"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1", "1.21", "1.21.1"]
datapack-folder = "./datapacks"
