name = "TorkenMon Pack Oficial 1.0.0-alpha"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ebcb2cc7371485cab7b447511b00348d9bc6690d893ec65e52b3db7cbeb5ac6"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1", "1.21", "1.21.1"]
datapack-folder = "./datapacks"
