name = "TorkenMon Pack Oficial 1.0.0-alpha"
author = "PerlandDev"
version = "1.0.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1e9369158fde9b8ed795fe465efb4c8664592951fb03f2dcd3c3a8caac39045"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1", "1.21", "1.21.1"]
datapack-folder = "./datapacks"
