# This is a basic workflow to help you get started with Actions

name: Torkenmon-prod
# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'


      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Export .mrpack file
        run: packwiz modrinth export --output torkenmon-server.mrpack

      # Define the version from the tag
      - name: Set version tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

 # Build the base image using itzg/minecraft-server
      - name: Build custom Minecraft server image
        run: |
          # Pull the base Minecraft server image
          docker pull itzg/minecraft-server:latest

          # Create a container from the base image
          docker create --name temp-container itzg/minecraft-server:latest

          # Copy the .mrpack file into the container (assume it was generated in the previous step)
          docker cp torkenmon-server.mrpack temp-container:/mods/torkenmon-server.mrpack

          # Commit the changes to create a new custom image
          docker commit temp-container estoesmoises/torkencraft:torkenmon-${{ env.VERSION }}

          # Push the new image to Docker Hub
          docker push estoesmoises/torkencraft:torkenmon-${{ env.VERSION }}

          # Remove the temporary container
          docker rm temp-container
